output "ssh_key_name" {
  value       = aws_key_pair.ssh_key[*].key_name
  description = "The name of the SSH key generated by Terraform."
}

output "server_using_custom_gameusersettingsini" {
  value       = var.use_custom_gameusersettings
  description = "Is the server using custom GameUserSettings.ini."
}

output "server_using_custom_gameini" {
  value       = var.use_custom_game_ini
  description = "Is the server using custom Game.ini."
}

output "server_is_password_protected" {
  value       = var.is_password_protected
  description = "Is the server password protected."
}

output "join_password" {
  value       = var.join_password
  description = "The server join password required to join."
}

output "max_players" {
  value       = var.max_players
  description = "The configured max players."
}

output "steam_query_port" {
  value       = var.steam_query_port
  description = "The configured steam query port."
}

output "game_client_port" {
  value       = var.game_client_port
  description = "The configured game client port."
}

output "admin_commands_password" {
  value       = var.server_admin_password
  description = "The configured admin command password."
}

output "session_name" {
  value       = var.ark_session_name
  description = "The configured session name."
}

output "custom_ini_s3_bucket_name" {
  value       = aws_s3_bucket.ark[*].id
  description = "The ID of the S3 bucket that was created if use custom ini with s3 was configured."
}

output "custom_gameusersettings_file_name" {
  value       = aws_s3_object.gameusersettings[*].key
  description = "The custom gameusersettings file name that was uploaded to s3 if use custom GUS ini with s3 was configured."
}

output "custom_game_file_name" {
  value       = aws_s3_object.gameini[*].key
  description = "The custom gameusersettings file name that was uploaded to s3 if use custom Game.ini with s3 was configured."
}


output "gameusersettings_s3_content" {
  value       = aws_s3_object.gameusersettings[*].content
  description = "The contents of the GameUserSettings.ini ( experimental )."
}


output "gameusersettings_s3_bucket" {
  value       = aws_s3_object.gameusersettings[*].bucket
  description = "The download URI of the gameusersettings.ini from s3 ( experimental )."
}

output "ark_server_public_ip" {
  value       = aws_eip.ark_server_ip.public_ip
  description = "The public IP address of the Ark server to connect on."
}

output "session_manager_enabled" {
  value       = var.enable_session_manager
  description = "Is AWS SSM Session Manager enabled or not."
}