output "backup_s3_bucket_name" {
  value       = module.asa.backup_s3_bucket_name
  description = "The ID of the S3 bucket created for backups if enabled."
}

output "backup_s3_bucket_arn" {
  value       = module.asa.backup_s3_bucket_arn
  description = "The ARN of the S3 bucket created for backups if enabled."
}

output "ssh_key_name" {
  value       = module.asa.ssh_key_name
  description = "The name of the SSH key generated by Terraform."
}

output "server_using_custom_gameusersettingsini" {
  value       = module.asa.server_using_custom_gameusersettingsini
  description = "Is the server using custom GameUserSettings.ini."
}

output "server_using_custom_gameini" {
  value       = module.asa.server_using_custom_gameini
  description = "Is the server using custom Game.ini."
}

output "server_is_password_protected" {
  value       = module.asa.server_is_password_protected
  description = "Is the server password protected."
}

output "join_password" {
  value       = module.asa.join_password
  description = "The server join password required to join."
}

output "max_players" {
  value       = module.asa.max_players
  description = "The configured max players."
}

output "steam_query_port" {
  value       = module.asa.steam_query_port
  description = "The configured steam query port."
}

output "game_client_port" {
  value       = module.asa.game_client_port
  description = "The configured game client port."
}

output "admin_commands_password" {
  value       = module.asa.admin_commands_password
  description = "The configured admin command password."
}

output "session_name" {
  value       = module.asa.session_name
  description = "The configured session name."
}

output "custom_ini_s3_bucket_name" {
  value       = module.asa.custom_ini_s3_bucket_name
  description = "The ID of the S3 bucket that was created if use custom ini with s3 was configured."
}

output "custom_gameusersettings_file_name" {
  value       = module.asa.custom_gameusersettings_file_name
  description = "The custom gameusersettings file name that was uploaded to s3 if use custom GUS ini with s3 was configured."
}

output "vpc_id" {
  value       = module.asa.vpc_id
  description = "The ID of the VPC created by Terraform."
}

output "subnet_id" {
  value       = module.asa.subnet_id
  description = "The subnet ID of the subnet created by Terraform."
}

output "security_group_id" {
  value       = module.asa.security_group_id
  description = "The security group ID of the security group created by Terraform."
}

output "ark_server_public_ip" {
  value       = module.asa.ark_server_public_ip
  description = "The public IP address of the Ark server to connect on."
}